version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    build: .
    container_name: php
    volumes: 
      - ./:/code
    depends_on:
      - db


  db:
    image: postgres
    container_name: cadoles_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cadoles
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 18080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db


volumes:
  pgdata: